name: Update QA Stand in CLoudFlare Pages
on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ["self-hosted", "k8s-prod"]
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install modules
        run: |
          yarn install
      - name: install aws cli
        run: sudo snap install aws-cli --classic
      # - name: Check external links
      #   run: |
      #     find ./README.md ./docs/ -regex ".*.[md|mdx]" -print0 | xargs -0 -n1 \
      #     ./node_modules/markdown-link-check/markdown-link-check --config linkcheck.config.json -q
      - name: Build
        run: |
          yarn clear
          yarn build


      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.TEST_CLOUDFLARE_API_TOKEN }}
          command: |
            pages deploy ./build --project-name="neon-evm-docs-test"
